### ISSUE TITLE
1 [B2] Administrative functions have redundant validations

### ISSUE THREAD

**Issue by ACassimiro** [soroswap/aggregator#46]
On the Aggregator's administrative functions, all operations start by performing a set of checks mainly comprised of two function calls: `check_initialized(&e)?;` and `check_admin(&e)?;`. The first one is not necessary, except for the `set_admin` function. 

An aggregator contract in its current state can only have an admin if `set_admin` is called or if the contract is initialized. Once an admin is set in the contract storage, it cannot be removed, only updated. This means that, given that the Aggregator's administrative functions first validate if the contract is initialized, and then check if an admin address has been set in the contract's storage before checking if the caller is indeed the protocol's administrator, the second check will always return true if the first one is true, making it redundant. The only exception to this is the `set_admin` function, which ideally should not be called before the contract initialization.

**Comment by esteblock** [comment]
Because get_admin returns the same NotInitialized error when the admin has not been set (and hence, not initialized)
```
pub fn get_admin(e: &Env) -> Result<Address, AggregatorError> {
    match e.storage().instance().get(&DataKey::Admin) {
        Some(admin) => Ok(admin),
        None => Err(AggregatorError::NotInitialized),
    }
}
```
All administrative functions will only have `check_admin(&e)?;` and we will drop `check_initialized(&e)?;`

This is for
- `update_adapters`
- `remove_adapter`
- `set_pause`
- `set_admin`
- `upgrade`
