### ISSUE TITLE
1 [A2] Malformed paths for distributions are allowed

### ISSUE THREAD

**Issue by ACassimiro** [soroswap/aggregator#48]
All responsibility of forming the paths for the distribution is currently delegated to the caller or the entity that builds the transactions calling the Aggregator. This means that paths for distribution allow, for instance:
  1. Swap sequences that start and end in the same asset;
  2. Different distributions with different starting and ending assets in their paths;
  3. Repeated sequences in a single path (i.e., token A -> token B -> token A -> token B);

While it is understandable that the official front-end of the Soroswap will correctly build the transactions and that misbehaviors are unlikely to happen, eventual updates or potential bugs in its path-finding algorithm may serve malformed paths in transactions to users. More likely are also the cases where a user trying to interact with the contract using self-developed scripts, which can submit transactions to the aggregator contract causing potential losses to this user. 

Furthermore, checks such as the one preventing a scenario shown in topic 1 above can stop the logic from lines 383 to 388 in the Aggregator contract from malfunctioning. 

Although this is not necessary, handling cases like the above can prevent corner cases from causing a bad user experience on the Soroswap platform. It is also needed to take into consideration which (if any) scenarios should be handled, as computationally intensive implementations could impact the price of transactions.

**Comment by esteblock** [comment]
Recommendation
To prevent users from incurring losses due to interactions with the Aggregator, it is important to
validate that the distribution paths respect rules regarding their integrity, for instance, enforcing
that the paths start and end in the assets specified as input and output for the swap functions
and that a path cannot start and end in the same token.
Although this is not mandatory, handling scenarios like the ones above can prevent corner
cases from causing a bad user experience on the Soroswap platform. It is also needed to take
into consideration which (if any) scenarios should be handled, as computationally intensive
implementations could impact the price of transactions.

**Comment by esteblock** [comment]
- [ ] Swap should not start and end in the same asset.
- [ ] All distributions should have the same start and same end

**Comment by esteblock** [comment]
Before changes
```
running 1 test
initialize()                                             | cpu: 162666,      mem: 67103
update_adapters()                                        | cpu: 186891,      mem: 57648
set_pause()                                              | cpu: 206883,      mem: 62091
set_admin()                                              | cpu: 179489,      mem: 59268
swap_exact_tokens_for_tokens(s_p_protocol_one_hop)       | cpu: 22706373,    mem: 13806897
-----------------------------------
swap_exact_tokens_for_tokens(1_protocol_one_hop)       | cpu: 12642395,    mem: 7178668
swap_exact_tokens_for_tokens(2_protocol_one_hop)       | cpu: 24998018,    mem: 14272561
swap_exact_tokens_for_tokens(3_protocol_one_hop)       | cpu: 37345807,    mem: 21368238
swap_exact_tokens_for_tokens(4_protocol_one_hop)       | cpu: 49725961,    mem: 28465699
swap_exact_tokens_for_tokens(5_protocol_one_hop)       | cpu: 62082489,    mem: 35564944
swap_exact_tokens_for_tokens(6_protocol_one_hop)       | cpu: 74449626,    mem: 42665973
-----------------------------------
swap_exact_tokens_for_tokens(1_protocol_two_hop)       | cpu: 20241401,    mem: 11011410
swap_exact_tokens_for_tokens(2_protocol_two_hop)       | cpu: 40178453,    mem: 21936793
swap_exact_tokens_for_tokens(3_protocol_two_hop)       | cpu: 60112936,    mem: 32865048
swap_exact_tokens_for_tokens(4_protocol_two_hop)       | cpu: 80065106,    mem: 43796175
swap_exact_tokens_for_tokens(5_protocol_two_hop)       | cpu: 100003375,    mem: 54730174
swap_exact_tokens_for_tokens(6_protocol_two_hop)       | cpu: 119890055,    mem: 65667045
-----------------------------------
swap_tokens_for_exact_tokens(1_protocol_one_hop)       | cpu: 12675051,    mem: 7194308
swap_tokens_for_exact_tokens(2_protocol_one_hop)       | cpu: 25043954,    mem: 14299097
swap_tokens_for_exact_tokens(3_protocol_one_hop)       | cpu: 37409667,    mem: 21405670
swap_tokens_for_exact_tokens(4_protocol_one_hop)       | cpu: 49810777,    mem: 28514027
swap_tokens_for_exact_tokens(5_protocol_one_hop)       | cpu: 62190171,    mem: 35624168
swap_tokens_for_exact_tokens(6_protocol_one_hop)       | cpu: 74503404,    mem: 42736093
-----------------------------------
swap_tokens_for_exact_tokens(1_protocol_two_hop)       | cpu: 20267633,    mem: 11033578
swap_tokens_for_exact_tokens(2_protocol_two_hop)       | cpu: 40212723,    mem: 21976385
swap_tokens_for_exact_tokens(3_protocol_two_hop)       | cpu: 60163422,    mem: 32922064
swap_tokens_for_exact_tokens(4_protocol_two_hop)       | cpu: 80125402,    mem: 43870615
swap_tokens_for_exact_tokens(5_protocol_two_hop)       | cpu: 100084329,    mem: 54822038
swap_tokens_for_exact_tokens(6_protocol_two_hop)       | cpu: 120089739,    mem: 65776333
-----------------------------------
remove_adapter()                                         | cpu: 258224,      mem: 76105

```
