### ISSUE TITLE
Setup mainnet deployment script with real soroswap and phoenix address

### ISSUE THREAD

**Issue by esteblock** [soroswap/aggregator#53]
Currently deployment works fine in Testnet.
Make it work correctly in Mainnet with mainnet deployment address

**Comment by MPSxDev** [comment]
Hello @esteblock , is this issue available? I would love to take it on and can start working immediately.

**Comment by esteblock** [comment]
> Hello @esteblock , is this issue available? I would love to take it on and can start working immediately.

Hello @MPSxDev sorry, this issue should be closed. I am closing it now.
Check issues with the ODHack9 tag.
Mostly on

https://github.com/soroswap/frontend/issues
and in 
https://github.com/soroswap/info/issues
