### ISSUE TITLE
2 Agregator manual testing: Add liquidity in: [Soroswap, Phoenix]

### ISSUE THREAD

**Issue by chopan123** [soroswap/aggregator#58]

**Comment by MattPoblete** [comment]
The goal is to create diferent pools and add a fixed amount of liquidity for each one.
Tasks:
- [ ] Create soroswap pools A-B, B-C, A-C.
- [ ] Create phoenix pools A-B, B-C, A-C.
- [ ] Add Liquidity to each Soroswap pool.
- [ ] Add Liquidity to each Phoenix pool.

**Comment by MattPoblete** [comment]
- 🪐 [`Soroswap factory docs`](https://github.com/Phoenix-Protocol-Group/phoenix-contracts/tree/main/contracts/factory)
- 🐦‍🔥 [`Phoenix factory docs`](https://github.com/Phoenix-Protocol-Group/phoenix-contracts/tree/main/contracts/factory)
