### ISSUE TITLE
1 Create Script to add Liquidity to Phoenix

### ISSUE THREAD

**Issue by esteblock** [soroswap/aggregator#73]
We want to use the same test tokens from the /core repo.
This is not ment to be a manual test, where liquidity is 100% controlled.
This is ment to be just a script where we can add liquidity for specific tokens in order to test the Aggregator in the frontend.

- [x] Add minter admin secret key in .env same minter admin secret key from ./core
- [x] Create script
- [ ] Please write documentation in README

**Comment by joaquinsoza** [comment]
@MattPoblete Just document how `protocols/phoenix/*` works and how it adds liquidity with the soroswap test tokens

**Comment by esteblock** [comment]
https://github.com/soroswap/core/blob/main/scripts/multi_add_liquidity.ts

**Comment by MattPoblete** [comment]
Updated PR
