### ISSUE TITLE
Create Adapter for Blend Backstop 80:20 Commet AMM

### ISSUE THREAD

**Issue by esteblock** [soroswap/aggregator#88]
Intro:

- Commet was a AMM project that reached an audited version of the Contracts but did not launch as a dApp
- The Blend Team used the repo https://github.com/mootz12/comet-contracts-v1/tree/ef4cbfad0a35202ad267c14d163d2f362995a8d3 to deploy a pool for their Backstop
- Read more about Backstop: https://docs.blend.capital/users/backstopping#what-are-blnd-usdc-80-20-liquidity-pool-shares

Currently there is the
 Commet Factory: https://stellar.expert/explorer/public/contract/CA2LVIPU6HJHHPPD6EDDYJTV2QEUBPGOAVJ4VIYNTMFUCRM4LFK3TJKF?filter=interface
 
 BLND/USDC 80:20 LP Pool
 https://stellar.expert/explorer/public/contract/CAS3FL6TLZKDGGSISDBWGGPXT3NRR4DYTZD7YOD3HMYO6LTJUVGRVEAM
 
 The LP Pool currently has a bit less than 900k TVL, the highest TVL for BLND currently on Stellar.
 
 
 What we need: Create an adaptor for this weighted pool and add it into the Soroswap Aggregator

**Comment by rahimklaber** [comment]
Can I be assigned to this?
