### ISSUE TITLE
Aggregator returns [] if the swap is through phoenix

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/aggregator#9]
Phoenix proxy is returning an empty [] where soroswap returns the amounts swapped, This affects the response showed in the frontend

![Image](https://github.com/soroswap/aggregator/assets/34905663/b0f02315-cc6d-4698-a4b6-6836ec28570d)

**Comment by joaquinsoza** [comment]
We need to return same as soroswap router

**Comment by esteblock** [comment]
The aggregator returns the results given by each adapter.
I added in the Phoenix adapter to return (amount in, amount out) regardeless of the amount of hops.
So this issue has been fixed.
